name: Deploy (Self-hosted + DB prod secrets)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    environment: prod   # 👈 usa los secrets del environment "prod"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env with DB secrets (prod)
        shell: bash
        run: |
          set -euo pipefail
          ENV_PATH=".env"

          cat > "$ENV_PATH" <<EOF
DB_HOST=${{ secrets.DB_HOST }}
DB_NAME=${{ secrets.DB_NAME }}
DB_USER=${{ secrets.DB_USER }}
DB_PASS=${{ secrets.DB_PASS }}
EOF

          chmod 600 "$ENV_PATH"

      - name: Build & Up with docker-compose
        shell: bash
        run: |
          set -e
          docker-compose down --remove-orphans || true
          docker-compose up -d --build
          docker-compose ps
          docker logs --tail 50 taxi_dashboard || true
